language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
os:
- linux
- osx
env: 
  global:
    - PACKAGE=biokepi INSTALL=true TESTS=false
  matrix:
    - OCAML_VERSION=4.02